DROP TABLE IF EXISTS CUSTOMER;
  
CREATE TABLE CUSTOMER (
  CUST_ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) DEFAULT NULL,
  AGE INT DEFAULT NULL,
  PHONE BIGINT DEFAULT NULL,
  IS_ACTIVE BOOLEAN
);

DROP TABLE IF EXISTS ACCOUNT;
  
CREATE TABLE ACCOUNT (
  ACC_ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  ACC_TYPE VARCHAR(250) NOT NULL,
  BALANCE DECIMAL NOT NULL,
  IS_JOINT_ACCOUNT BOOLEAN,
  CUST_ID INT NOT NULL,
  foreign key (CUST_ID) references CUSTOMER(CUST_ID)
);

DROP TABLE IF EXISTS ADDRESS;
  
CREATE TABLE ADDRESS (
  ADDR_ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  CITY VARCHAR(250) DEFAULT NULL,
  STATE VARCHAR(250) DEFAULT NULL,
  COUNTRY VARCHAR(250) DEFAULT NULL,
  ZIPCODE BIGINT DEFAULT NULL,
  CUST_ID INT NOT NULL,  
  foreign key (CUST_ID) references CUSTOMER(CUST_ID)
);
